Repository PaddlePaddle/PaddleOCR, pull requests merged in 2022-03, with the labels that each got.

#5368 Add FCENet
  configs/det/det_r50_dcn_fce_ctw.yml
  doc/doc_ch/algorithm_overview.md
  ppocr/data/imaug/__init__.py
  ppocr/data/imaug/fce_aug.py
  ppocr/data/imaug/fce_targets.py
  ppocr/data/imaug/operators.py
  ppocr/losses/__init__.py
  ppocr/losses/det_fce_loss.py
  ppocr/metrics/__init__.py
  ppocr/metrics/det_metric.py
  ppocr/modeling/backbones/det_resnet_vd.py
  ppocr/modeling/heads/__init__.py
  ppocr/modeling/heads/det_fce_head.py
  ppocr/modeling/necks/__init__.py
  ppocr/modeling/necks/fce_fpn.py
  ppocr/postprocess/__init__.py
  ppocr/postprocess/fce_postprocess.py
  ppocr/utils/poly_nms.py
  tools/program.py
Labels: third party

#5545 update paddle2onnx readme
  deploy/paddle2onnx/images/lite_demo_onnx.png
  deploy/paddle2onnx/images/lite_demo_paddle.png
  deploy/paddle2onnx/readme.md
Labels: third party

#5638 Update recognition.md
  doc/doc_ch/recognition.md
Labels: third party

#5700 [Detection]add FECNet inference
  configs/det/det_mv3_pse.yml
  configs/det/det_r50_vd_dcn_fce_ctw.yml
  configs/det/det_r50_vd_pse.yml
  ppocr/modeling/heads/det_fce_head.py
  ppocr/postprocess/fce_postprocess.py
  ppocr/postprocess/pse_postprocess/pse_postprocess.py
  tools/infer/predict_det.py
  tools/infer/utility.py
Labels: Detection

#5784 update pgnet.md
  doc/doc_ch/pgnet.md
  doc/doc_en/pgnet_en.md
Labels: contributor, status: proposed
