Repository PaddlePaddle/PaddleOCR, pull requests merged in 2022-06, with the labels that each got.

#6477 Fix copy_paste no texts augment.
  ppocr/data/imaug/copy_paste.py
Labels: contributor, status: proposed

#6361 Update README_en.md
  deploy/slim/quantization/README_en.md
Labels: contributor, status: proposed

#6604 fix DeprecationWarning,
  tools/infer/utility.py
Labels: third party, contributor, status: proposed

#5616 add chinese handwriteen dataset scut-ept
  doc/datasets/SCUT_0.jpg
  doc/doc_ch/handwritten_datasets.md
  doc/doc_en/handwritten_datasets_en.md
Labels: documentation, community

#6648 Fix SER and RE VQA docs command error
  ppstructure/vqa/README.md
  ppstructure/vqa/README_ch.md
Labels: contributor, status: proposed

#6575 update win doc
  deploy/cpp_infer/docs/windows_vs2019_build.md
Labels: community, contributor, status: proposed

#6650 Update native.cpp fix issue 6640
  deploy/android_demo/app/src/main/cpp/native.cpp
Labels: contributor, status: proposed

#6625 update sorted_boxes
  tools/infer/predict_system.py
Labels: contributor, status: proposed

#6488 fix multiprocess overwrite
  tools/infer/predict_system.py
Labels: community, contributor, status: proposed
