Repository PaddlePaddle/PaddleOCR, pull requests merged in 2023-10, with the labels that each got.

#10731 Update how_to_do_kie_en.md
  ppstructure/kie/how_to_do_kie_en.md
Labels: Contributor PR is merged

#11030 Update ONNX conversion readme_ch.md
  deploy/paddle2onnx/readme.md
  deploy/paddle2onnx/readme_ch.md
Labels: contributor

#11069 Cherrypicking GH-10923 to PaddleOCR:dygraph
  PPOCRLabel/gen_ocr_train_val_test.py
Labels: contributor

#10732 Update quickstart_en.md
  ppstructure/docs/quickstart_en.md
Labels: Contributor PR is merged

#10733 Update README.md
  ppstructure/kie/README.md
Labels: amp, Contributor PR is merged

#10734 Update algorithm_overview_en.md
  doc/doc_en/algorithm_overview_en.md
Labels: amp, Contributor PR is merged

#11107 修复代码错误
  ppstructure/utility.py
Labels: contributor

#11125 update uygur dict
  ppocr/utils/dict/ug_dict.txt
Labels: contributor, Contributor PR is merged
