Repository PaddlePaddle/PaddleOCR, pull requests merged in 2023-11, with the labels that each got.

#11238 fix SAR inference, when batch size>1, norm_img_batch and valid_ratios…
  tools/infer/predict_rec.py
Labels: contributor, Contributor PR is merged

#11258 v4 det cml configs
  configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml
Labels: contributor

#11280 解決recognition的train test分割程式執行後的文檔每行間多出一行空格
  PPOCRLabel/gen_ocr_train_val_test.py
Labels: Contributor PR is merged

#11287 Fix for Ambiguous Boolean Evaluation Error in PaddleOCR with Python 3.11
  paddleocr.py
Labels: Contributor PR is merged

#11299 Fix bug when running on XPU
  tools/program.py
Labels: contributor

#11301 Dygraph
  tools/program.py
Labels: contributor
