Repository PaddlePaddle/PaddleOCR, pull requests merged in 2023-09, with the labels that each got.

#10749 Update setup.py
  setup.py
Labels: Contributor PR is merged

#10653 Update v4 det model path in README.md
  README.md
Labels: contributor

#10810 Fix index variable in for loop in paddlestructure.cpp
  deploy/cpp_infer/src/paddlestructure.cpp
Labels: contributor

#10892 rec_r45_abinet for export model
  configs/rec/rec_r45_abinet.yml
  tools/export_model.py
Labels: contributor

#10847 fix:修复通道数不匹配造成的PPOCRLabel启动失败问题#10748,根据更新日志发现#10655，由于paddleocr中增加了对…
  paddleocr.py
Labels: contributor

#10850 add finnish language files
  ppocr/utils/corpus/fi_corpus.txt
  ppocr/utils/dict/fi_dict.txt
Labels: contributor, Contributor PR is merged

#10990 [New] add rec CPPD model
  configs/rec/rec_svtrnet_cppd_base_ch.yml
  configs/rec/rec_svtrnet_cppd_base_en.yml
  doc/doc_ch/algorithm_overview.md
  doc/doc_ch/algorithm_rec_cppd.md
  doc/doc_en/algorithm_overview_en.md
  doc/doc_en/algorithm_rec_cppd_en.md
  ppocr/data/imaug/label_ops.py
  ppocr/losses/__init__.py
  ppocr/losses/rec_cppd_loss.py
  ppocr/modeling/heads/__init__.py
  ppocr/modeling/heads/rec_cppd_head.py
  ppocr/modeling/heads/rec_nrtr_head.py
  ppocr/postprocess/__init__.py
  ppocr/postprocess/rec_postprocess.py
  tools/export_model.py
  tools/infer/predict_rec.py
  tools/program.py
Labels: contributor

#10735 Update kie_datasets_en.md
  doc/doc_en/dataset/kie_datasets_en.md
Labels: Contributor PR is merged
