Repository PaddlePaddle/PaddleOCR, pull requests merged in 2023-08, with the labels that each got.

#10489 Fix bug in run PP-OCRv3 rec with dygraph branch code
  configs/rec/PP-OCRv3/ch_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml
  configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/arabic_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/chinese_cht_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/cyrillic_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/devanagari_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/japan_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/ka_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/latin_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/ta_PP-OCRv3_rec.yml
  configs/rec/PP-OCRv3/multi_language/te_PP-OCRv3_rec.yml
Labels: status: proposed

#10514 fix bug for table_master in tipc when running 'lite_train_lite_infer' mode
  test_tipc/prepare.sh
Labels: contributor, status: proposed

#10502 remove un-used imported modules, so to avoid PyInstaller packaged binary runtime error
  ppocr/data/imaug/ct_process.py
  ppocr/utils/utility.py
Labels: contributor, status: proposed

#10493 Fixed Layout recovery README file
  ppstructure/recovery/README.md
Labels: contributor, status: proposed

#10441 fix memory leak
  deploy/cpp_infer/include/paddleocr.h
  deploy/cpp_infer/include/paddlestructure.h
  deploy/cpp_infer/src/main.cpp
  deploy/cpp_infer/src/paddleocr.cpp
  deploy/cpp_infer/src/paddlestructure.cpp
Labels: contributor, status: proposed

#10512 Usinig intuitive initialization of duration
  deploy/cpp_infer/src/ocr_cls.cpp
  deploy/cpp_infer/src/ocr_rec.cpp
Labels: contributor, status: proposed

#10593 [Cherry-pick] #10441 #10512
  deploy/cpp_infer/include/paddleocr.h
  deploy/cpp_infer/include/paddlestructure.h
  deploy/cpp_infer/src/main.cpp
  deploy/cpp_infer/src/ocr_cls.cpp
  deploy/cpp_infer/src/ocr_rec.cpp
  deploy/cpp_infer/src/paddleocr.cpp
  deploy/cpp_infer/src/paddlestructure.cpp
Labels: contributor, status: proposed

#10655 Cherrypicking GH-10217 and GH-10216 to PaddlePaddle:Release/2.7
  paddleocr.py
  ppocr/utils/utility.py
  ppstructure/utility.py
  tools/infer/predict_system.py
  tools/infer/utility.py
Labels: contributor, status: proposed

#10656 Update requirements.txt to add missing pyyaml library
  requirements.txt
Labels: contributor, status: proposed

#10662 修改数据增强导致的DSR报错
  .pre-commit-config.yaml
  ppocr/data/simple_dataset.py
Labels: contributor, status: proposed

#10668 onnxruntime support gpu
  tools/infer/utility.py
Labels: contributor, status: proposed

#10681 修改数据增强导致的DSR报错 (#10662)
  .pre-commit-config.yaml
  ppocr/data/simple_dataset.py
Labels: contributor, status: proposed

#10670 fix typo in algorithm_overview_en.md
  doc/doc_en/algorithm_overview_en.md
Labels: contributor, status: proposed

#10628 实现功能：当--savefile为true时，在--output下以当前图片名称后接“.txt”为文件名保存ocr推理结果，解决了issues：
  paddleocr.py
Labels: contributor, Contributor PR is merged

#10654 Cherrypicking GH-10217 and GH-10216 to PaddlePaddle:dygraph
  paddleocr.py
  ppocr/utils/utility.py
  ppstructure/utility.py
  tools/infer/predict_system.py
  tools/infer/utility.py
Labels: contributor, Contributor PR is merged

#10690 Update how_to_do_kie_en.md
  ppstructure/kie/how_to_do_kie_en.md
Labels: contributor, status: proposed

#10704 Update algorithm_overview_en.md
  doc/doc_en/algorithm_overview_en.md
Labels: Contributor PR is merged

#10706 Update README.md
  ppstructure/kie/README.md
Labels: Contributor PR is merged

#10688 fix: release memory after predict
  tools/infer/predict_rec.py
Labels: contributor, Contributor PR is merged

#10744 rec_r45_abinet.yml add max_length and image_size
  configs/rec/rec_r45_abinet.yml
  ppocr/modeling/heads/rec_abinet_head.py
Labels: contributor

#10761 ch_PP-OCRv4_rec_distill.yml, fix KeyError: 'NRTRLabelDecode'
  tools/train.py
Labels: contributor

#10777 根据推理对三通道的图像需求，以及opencv中imread参数说明IMREAD_COLOR(If set, always convert …
  paddleocr.py
Labels: contributor
