Repository PaddlePaddle/PaddleOCR, pull requests merged in 2023-01, with the labels that each got.

#8755 Update README_日本語.md
  doc/doc_i18n/README_日本語.md
Labels: contributor, status: proposed

#8785 Fix typo and grammatical error
  ppstructure/kie/README.md
Labels: cherry pick

#8729 Fix broken link to install paddlepaddle
  doc/doc_en/quickstart_en.md
Labels: documentation, contributor, cherry pick

#8719 Fix: broken link for whl package documentation.
  ppstructure/docs/quickstart_en.md
Labels: contributor, status: proposed

#8821 Cherry-pick 3 commits from release/2.6 to dygraph
  doc/doc_en/quickstart_en.md
  ppstructure/docs/quickstart_en.md
  ppstructure/kie/README.md
Labels: contributor, status: proposed

#8876 Fix the mismatch of document between Chinese and English
  doc/doc_en/whl_en.md
Labels: contributor, status: proposed

#8918 Fix sorted_boxes() function bug: the index j can not skip 0.
  tools/infer/predict_system.py
Labels: contributor, status: proposed

#8920 新增gpu_id参数，可以在推理时使用特定GPU进行推理
  tools/infer/utility.py
Labels: contributor, status: proposed

#8569 Fix model download link in documentation
  doc/doc_en/algorithm_overview_en.md
  doc/doc_en/algorithm_rec_vitstr_en.md
Labels: contributor, status: proposed, cherry pick
